# Site settings
title: Warp 10
email: frostyplanet@localhost
description: > # this means to ignore newlines until "baseurl:"
    "Warp 10" is impossible speed in StarTrek universe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.warp10.info" # the base hostname & protocol for your site
#twitter_username:  ""
github_username:  frostyplanet

# Build settings
markdown: kramdown
